### ISSUE TITLE
验证码识别率多少

### ISSUE THREAD

**Issue by 7huahaha** [HelKim/cet_check_grade#1]
result_table()你都没改，其实svm的识别正确率也很高。关键是在对图片的处理

**Comment by HelKim** [comment]
准确率60-70左右，谢谢大佬的教程，让我学习了很多。

**Comment by 7huahaha** [comment]
微信 PhilSFate 是你吗

**Comment by HelKim** [comment]
不是

**Comment by 7huahaha** [comment]
你没有切割验证码吗

**Comment by HelKim** [comment]
有，不过现在那个网站的验证码好像更复杂了

**Comment by 7huahaha** [comment]
一样的，没有变，我也不是原作者。我只是在原作者基础上改了一下，你好像是在我网盘里下载了我改的代码

**Comment by HelKim** [comment]
哦哦，这样，谢谢。
